-- Supabase SQL Editor에서 실행
create table if not exists public.dashboard_datasets (
  id bigint generated by default as identity primary key,
  dataset_key text not null,
  file_name text,
  uploaded_by text,
  uploaded_at timestamptz default now(),
  row_count integer default 0,
  data jsonb not null
);

create index if not exists dashboard_datasets_key_time_idx
on public.dashboard_datasets (dataset_key, uploaded_at desc);

alter table public.dashboard_datasets enable row level security;

-- 테스트 단계용: 읽기 허용
drop policy if exists "public read dashboard datasets" on public.dashboard_datasets;
create policy "public read dashboard datasets"
on public.dashboard_datasets
for select
using (true);

-- 테스트 단계용: 업로드 허용
-- 운영 전에는 관리자 로그인 기반으로 제한 권장
drop policy if exists "public insert dashboard datasets" on public.dashboard_datasets;
create policy "public insert dashboard datasets"
on public.dashboard_datasets
for insert
with check (true);